// <auto-generated />
using System;
using GoalsTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoalsTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619234430_UpdateUserTable")]
    partial class UpdateUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("GoalsTracker.Models.CaseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasesClosed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateClosed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateClosed")
                        .IsUnique();

                    b.ToTable("CaseEntries");
                });

            modelBuilder.Entity("GoalsTracker.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutesWorked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogDate")
                        .IsUnique();

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("GoalsTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
